### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by mpdude** [DanHam/packer-virt-sysprep#1]
This seems to be what I am looking for. 

So, how do I integrate this with packer or run it?

**Comment by DanHam** [comment]
Hi Matthias,

Apologies for not having responded sooner. I will try and put together a small how-to guide for you this evening.

Regards,

Dan

**Comment by DanHam** [comment]
Hi Matthias,

Again, sorry for the delay. Please see the example repo I've created at https://github.com/DanHam/packer-virt-sysprep-example. That *should* hopefully explain everything. It's not quite the 'small' how-to guide promised since some other people have been asking for documentation on using these scripts as well. That said, I may have gotten a little carried away!! Regardless I hope it helps.

Best wishes,

Dan

**Comment by mpdude** [comment]
Awesome, thank you!
